apiVersion: v1
kind: Service
metadata:
  name: {{ include "dolibarr.fullname" . }}
  labels:
    helm.sh/chart: {{ include "dolibarr.chart" . }}
    app.kubernetes.io/name: {{ include "dolibarr.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- range $key, $value := .Values.extraLabels }}
    "{{ $key }}": "{{ $value }}"
    {{- end }}
spec:
  {{ $serviceType := .Values.service.type | default "ClusterIP" -}}
  type: {{ $serviceType }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
  - port: {{ .Values.service.http | default 80 }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if (and (eq $serviceType "NodePort") (not (empty .Values.service.httpNodePort))) }}
    nodePort: {{ .Values.service.httpNodePort | default 80 }}
    {{- end }}
  - port: {{ .Values.service.httpsPort | default 443 }}
    targetPort: https
    protocol: TCP
    name: https
    {{- if (and (eq $serviceType "NodePort") (not (empty .Values.service.httpsNodePort))) }}
    nodePort: {{ .Values.service.httpsNodePort | default 443 }}
    {{- end }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "dolibarr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
